// 供应商预设：官方 Base URL、协议、鉴权方式、常用模型推荐
export const VENDOR_PRESETS = [
  {
    id: 'aliyun',
    name: '阿里云百炼',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    anthropicUrl: 'https://dashscope.aliyuncs.com/apps/anthropic',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    hugeCatalog: true,
    description: '通义千问 + DeepSeek / GLM / Kimi 等三方模型',
    recommended: [
      { series: 'DeepSeek', note: '推理 / 编程', models: ['deepseek-v4-pro', 'deepseek-v4-flash', 'deepseek-r1', 'deepseek-v3'] },
      { series: 'GLM', note: '通用 / 编程', models: ['glm-5.2', 'glm-4.7', 'glm-4.6'] },
      { series: 'Kimi', note: '长上下文 / 文档', models: ['kimi/kimi-k3', 'kimi-k2.5', 'moonshot-v1-128k'] },
      { series: '通义千问', note: '官方全系列', models: ['qwen3.8-max', 'qwen3.7-plus', 'qwen3.7-flash'] },
      { series: '千问视觉 (支持看图)', note: '多模态 / 图像理解', models: ['qwen-vl-max', 'qwen-vl-plus', 'qwen2.5-vl-72b-instruct'] },
      { series: 'MiniMax', note: '三方直供', models: ['MiniMax/MiniMax-M3'] },
      { series: '小米', note: '三方直供', models: ['xiaomi/mimo-v2.5-pro'] },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek 官方',
    baseUrl: 'https://api.deepseek.com',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: 'DeepSeek 官方 API',
    recommended: [{ series: 'DeepSeek', note: '官方全系列', models: ['deepseek-chat', 'deepseek-reasoner'] }],
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '智谱开放平台',
    recommended: [
      { series: 'GLM 视觉 (支持看图)', note: '多模态 / 图像理解', models: ['glm-4v-plus', 'glm-4v', 'glm-4v-flash'] },
      { series: 'GLM 通用 / 编程', note: '官方全系列', models: ['glm-5.2', 'glm-4.7', 'glm-4.6', 'glm-4.5-air', 'glm-4-flash'] },
    ],
  },
  {
    id: 'moonshot',
    name: 'Moonshot Kimi',
    baseUrl: 'https://api.moonshot.cn/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '月之暗面 Kimi',
    recommended: [{ series: 'Kimi', note: '官方全系列', models: ['kimi-k2.5', 'kimi-k2-turbo-preview', 'moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'] }],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    protocol: 'openai',
    wireApi: 'responses',
    auth: 'bearer',
    description: 'OpenAI 官方 API',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    protocol: 'anthropic',
    wireApi: 'anthropic',
    auth: 'x-api-key',
    description: 'Anthropic 官方 API',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    protocol: 'gemini',
    wireApi: 'gemini',
    auth: 'x-goog-api-key',
    description: 'Google AI Studio 官方 API',
  },
  {
    id: 'ollama',
    name: 'Ollama（本地）',
    baseUrl: 'http://localhost:11434/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'none',
    description: '本地部署，无需 API Key',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '聚合多家厂商模型',
  },
  {
    id: 'siliconflow',
    name: '硅基流动 SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '国内模型聚合平台',
  },
  {
    id: 'volcengine',
    name: '火山方舟 Ark',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '字节跳动火山引擎',
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    baseUrl: 'https://api.x.ai/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: 'xAI 官方 API',
  },
  {
    id: 'groq',
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '超快推理，部分免费模型',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: 'Mistral 官方 API',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: 'MiniMax 官方 API',
  },
  {
    id: 'baidu',
    name: '百度千帆',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '百度智能云千帆',
  },
  {
    id: 'tencent',
    name: '腾讯混元',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '腾讯云混元大模型',
  },
  {
    id: 'custom',
    name: '自定义（OpenAI 兼容）',
    baseUrl: '',
    protocol: 'openai',
    wireApi: 'chat',
    auth: 'bearer',
    description: '任意 OpenAI 兼容网关 / 中转',
  },
];

export function getPreset(id) {
  return VENDOR_PRESETS.find((p) => p.id === id) || null;
}
